# This is a basic workflow to help you get started with Actions

name: Compile and test Lamscript release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test_on_linux:
    name: Build & test Lamscript on Linux with G++.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: ./scripts/setup.sh --within-ci true

      - name: Compile a release build of lamscript
        run: ./scripts/compile_lamscript.sh \
            --build Release \
            --cpp-compiler g++-10 \
            --cores 2

      - name: Run all of lamscripts tests.
        run: ./scripts/run_all_tests.sh --build Release

  build_and_test_on_macos:
    name: Build & test Lamscript on MacOS with G++.
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: ./scripts/setup.sh --within-ci true

      - name: Compile a release build of lamscript
        run: ./scripts/compile_lamscript.sh \
            --build Release \
            --cpp-compiler g++-10 \
            --cores 2

      - name: Run all of lamscripts tests.
        run: ./scripts/run_all_tests.sh --build Release

  build_and_test_on_windows:
    name: Build & test Lamscript on Windows.
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        shell: bash
        run: ./scripts/setup.sh --within-ci true

      - name: Setup mingw64.
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64

      - name: Compile a release build of lamscript
        shell: msys2 {0}
        run: sudo pacman --noconfirm -Syu gcc && ./scripts/compile_lamscript.sh \
            --build Release \
            --cpp-compiler g++ \
            --cores 2

      - name: Run all of lamscripts tests.
        shell: bash
        run: ./scripts/run_all_tests.sh --build Release
