# This is a basic workflow to help you get started with Actions

name: Compile and test Lamscript release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build & test Lamscript on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ g++ ]
        include:
          - os: ubuntu-latest
            compiler: g++
            target: Linux

          - os: macos-latest
            compiler: g++
            target: Macos

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run the projects setup.
        run: ./scripts/setup.sh --within-ci true

      - name: Add msbuild to PATH
        if: ${{ matrix.os == "windows-latest" }}
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Compile a release build of lamscript
        run: ./scripts/compile_lamscript.sh \
            --build Release \
            --cpp-compiler ${{ matrix.compiler }} \
            --os ${{ matrix.target }}
            --cores 2

      - name: Run all of lamscripts tests.
        run: ./scripts/run_all_tests.sh --build Release --os {{ matrix.target }}
