# This is a basic workflow to help you get started with Actions

name: Compile and test Lamscript release

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Cmake 10.2
        run: sudo apt-get install g++-10

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.4
        with:
          cmake-version: '3.16.x'

      - name: Run project setup
        run: ./scripts/setup.sh --within-ci true

      - name: Compile a release build of lamscript
        run: ./scripts/compile_lamscript.sh \
            --build Release \
            --cpp-compiler g++ \
            --cores 1

      - name: Run all of lamscripts tests.
        run: ./scripts/run_all_tests.sh --build Release
